Portfolio desktop site version
alexiscyber14/portfolio pull request #5
Opened 2023-01-17 19:59 UTC by alexiscyber14

Requirements:
Build a desktop version of the portfolio site.
Should use only HTML and CSS
Should have no linter errors
Should use flex and grid

Achievements:
I have created a branch called  portfolio-desktop-site-version
I have used only Html and CSS
Found no linter errors
I have used flex and grid

2023-01-17 20:43 UTC, anagudelogu requested changes
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @alexiscyber14 , 
I'm Andres.

_⚠️ Note: Please do not close or modify your pull requests after you submit your work so we CRs have an easier time reviewing your code._

While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻 
✅ Descriptive PR title, summary and commit messages. 💬 

## Required Changes ♻️
_Check the comments under the review._

- [ ] 🚧 Please consider fixing the link to your `LICENSE.md` file for your README. At the moment, you're linking to a `LICENSE` file but the link is broken because it's missing the `.md` extension! 🤓 🔧 
![Screenshot from 2023-01-17 15-40-53](https://user-images.githubusercontent.com/77069011/213008328-3376e6d7-dc47-4ab8-ab65-43b21e763350.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 20:43 UTC, anagudelogu commented on index.html
> +        </div></nav>
- [ ] Great job working on your toolbar! 💯 However, the spacing of the elements is not quite right. According to the Figma design, there should be a space to the left of the logo and the navigation links shouldn't have that much gap, please consider fixing this! 🤓 🔧 

|Template|Your design|
|---|---|
| ![image](https://user-images.githubusercontent.com/77069011/213001039-01a47186-7675-4faf-95fc-3efc58f2e438.png) | ![image](https://user-images.githubusercontent.com/77069011/213000920-3fd0e4d0-ea62-408d-9865-599404ab57d3.png) |

2023-01-17 20:43 UTC, anagudelogu commented on style.css
> +  }
- [ ] You did well in this section too 🚀 , the only suggestion I have is to use the proper font and font size. The title should use Crete Round font and be 72px. The subtitle should use Inter font and be 32px and the paragraph should use Inter font too. 🤓 🔧

2023-01-17 20:43 UTC, anagudelogu commented on style.css
> +  }
- [ ] Please make sure that every button on your page has the interaction effects hover, focus, etc. This will improve the user experience of your site, providing a more interactive UI to users. 🤓 🔧

![image](https://user-images.githubusercontent.com/77069011/213002668-7c69794d-39ac-44e9-a5c0-74b71e0339fc.png)

2023-01-17 20:43 UTC, anagudelogu commented on style.css
> +  }
- [ ] The about section is great but the list of skills, languages, and frameworks is not aligned. Please consider aligning it to stick as much as possible to the Figma design! 🤓 🔧 

|Template|Your design|
|---|---|
| ![image](https://user-images.githubusercontent.com/77069011/213006244-6c990153-a13a-4781-a90d-b3fe3a742409.png) | ![image](https://user-images.githubusercontent.com/77069011/213006174-f97d5347-8b9d-4a3a-b189-a08362fa9cd8.png) |

Also the section height is not supposed to be full-screen, please look into it! 🤓 🔧

2023-01-17 20:43 UTC, anagudelogu commented on style.css
> +  }
- [ ] This section has so much blank space at the top. Please consider removing it. Having a good-looking website will be more appealing to future recruiters and people looking at your work! Please fix this. 🤓 🔧 

|Template|Your design|
|---|---|
| ![image](https://user-images.githubusercontent.com/77069011/213007065-36707d59-6c07-4f22-9bd8-acb9ba476252.png) | ![image](https://user-images.githubusercontent.com/77069011/213007004-4c3c8338-8a39-4ba7-8b3f-78462cb63101.png) |


- [ ] Also consider fixing the color of the text, as it doesn't match the one in the design `#262626` 🤓 🔧

2023-01-17 20:43 UTC, anagudelogu commented on style.css
> +    left: 0;
- [ ] **[OPTIONAL]:** I noticed that you have multiple repeated CSS properties across your stylesheet. It would be great if you can find a way of reducing this duplication of code ♻️. Remember that not repeating pieces of code will keep your codebase clean and readable. 🤓 🛠️ 

From [HTML & CSS best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md):
![image](https://user-images.githubusercontent.com/77069011/200000947-9e58c4d8-fed4-45f8-a822-7828c6e713f7.png)


In this case, you could do this with flex:

```CSS
.flex {
  display: flex;
}
``` 

And then, use it in your HTML elements where you need a flex container:

```HTML
<div class="flex"> This is a flex container </div>
```

Please, consider fixing this! 🤓

2023-01-17 22:15 UTC, NahnahAJ reviewed
Hi @alexiscyber14 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has a closed pull request please reopen the PR and resubmit the project for review. :+1: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-18 05:58 UTC, topeogunleye requested changes
> # Changes Required 
> ### Hi @alexiscyber14,
> Nice job, you are almost there.
> 
> ![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
> 
> ## (Highlights) Good Points: 
> * Good commit messages. :heavy_check_mark:
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
> * Professional README file. :heavy_check_mark:
> * PR has a good summary description :heavy_check_mark:
>
> ## (Changes Required) Aspects to improve: 
> * [ ]  Please check my inline comments.
> 
> ## [Optional] suggestions:
> * Nothing to mention.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> **Cheers and Happy coding! :clap::clap::clap:**
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear
> Please, remember to tag @topeogunleye in your question so I can receive the notification.
>
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-01-18 05:58 UTC, topeogunleye commented on README.md
> +This project is [MIT] (./LICENSE) licensed.
- [ ] There shouldn't be a space between [MIT] and (./LICENCE). This will ensure the markup is written correctly and that it  works.

✔️ Correct
`[MIT](./LICENSE)`

❌ Incorrect
`[MIT] (./LICENSE)`

2023-01-18 05:58 UTC, topeogunleye commented on style.css
> +    font-family: "Poppins", sans-serif;
- [ ] As suggested by the previous code reviewer, please make use of 'inter' font for your welcome section paragraph.

2023-01-18 05:58 UTC, topeogunleye commented on style.css
> +  .welcome .intro .help-text {
- [ ] As suggested by the previous code reviewer, please make use of 'inter' font here.

2023-01-18 05:58 UTC, topeogunleye commented on style.css
> +  .work-details button {
- [ ] Ad suggested by the previous reviewer, I kindly recommend that you add the pressed state interactions for your button. 

the button on the pressed state has the `background: #E05304`

### EXAMPLE:
**for pressed state**
```
button:active {
   background-color: #E05304;
}

2023-01-18 05:58 UTC, topeogunleye commented on style.css
> +  .about-me {
- [ ] Great job aligning the about me section as suggested, but please also make sure the height of this section is not full page as suggested by the previous reviewer and as seen from the Figma design.

2023-01-18 06:12 UTC, alexiscyber14 commented on style.css
> +  .about-me {
But then am designing for a desktop/ full screen. what do you mean by not a full page yet the requirement sayss full screen?

2023-01-18 06:47 UTC, topeogunleye commented on style.css
> +  .about-me {
@alexiscyber14, from the figma design, the languague and framework take up about only half of the page in the Figma Design, but for yours, it takes the full page. I can see that you have made corrections but your horizontal bar is gone now, please fix it and bring it back.

2023-01-18 06:50 UTC, topeogunleye commented on style.css
> +  }
@anagudelogu , please don't forgot to add the pressed button interaction

2023-01-18 06:57 UTC, alexiscyber14 commented on style.css
> +  .about-me {
I have made the changes. Thank you!

2023-01-18 07:17 UTC, Tadesse-Alemayehu requested changes
### Hi @alexiscyber14 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![212094426-b41dd457-c9db-4ab3-bbe9-176dd8dd08b7](https://user-images.githubusercontent.com/69077061/212385281-4797c58a-d358-423a-aa7c-832c22203865.gif)

## Highligts
 - [ ] Good job overall following the template design ✅
 - [ ] Good job making most of the changes requested by the previous code reviewer. ✅
 - [ ]  Correct GitHub Flow  ✅
 - [ ]  All linters passed  ✅
 
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 07:17 UTC, Tadesse-Alemayehu commented on style.css
> +  }
- [ ] Good job adding the hover effects for the button @alexiscyber14, But as the previous reviewer mentioned we also need to set the  `pressed` button interaction for the buttons. This is to make sure you have a design that feels the same as the Figma design.
![](https://user-images.githubusercontent.com/77069011/213002668-7c69794d-39ac-44e9-a5c0-74b71e0339fc.png)

2023-01-18 07:17 UTC, Tadesse-Alemayehu commented on index.html
> +
- [ ] Dear @alexiscyber14, Good job making the suggested changes, And your design is looking great already. But in doing so I see that you have removed the horizontal like from the view, This is required to make your design close to the Figma design. Please address this.

### Figma design 
![Screenshot 2023-01-18 100942](https://user-images.githubusercontent.com/69077061/213107259-83c4b478-f935-42c9-9be1-ac9d3bb6064e.png)

### Your design 
![Screenshot 2023-01-18 100955](https://user-images.githubusercontent.com/69077061/213107265-1c5bc517-8103-4aaf-802c-f9f3612d9983.png)

2023-01-18 07:29 UTC, alexiscyber14 commented on index.html
> +
I have added the line

2023-01-18 07:41 UTC, Shedrack-Sunday approved these changes
Hi @alexiscyber14   👋 
 
 # STATUS: APPROVED ✔️  🍾  🥳

 Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉

 ![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)
 
 ## Highlights
- Proper use of Github features 💯 
- Good commit messages 
 
 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
 

 Cheers and Happy coding!👏👏👏
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 09:12 UTC, topeogunleye commented on style.css
> +  .about-me {
you're welcome

2023-01-19 09:09 UTC, merged